services:
    # A web service running the Flask API
    - type: web
      name: pet-ml-api
      env: python
      buildCommand: chmod +x ./setup_for_render.sh ./build.sh && (./setup_for_render.sh || ./build.sh)
      startCommand: cd ml_models && gunicorn --log-file=- wsgi:app
      envVars:
          - key: PYTHON_VERSION
            value: 3.9.16
          - key: PYTHONPATH
            value: .:/app
      healthCheckPath: /health
